plugins: rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  DisabledByDefault: true
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*
    - node_modules/**/*
    - bin/*

Bundler/OrderedGems:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
